[package]
name = "cargo-atest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4", features = ["derive"] }
reqwest = {version = "0.12.20", features = ["blocking"]}
scraper = "0.23.1"



